# Generated by Django 4.1.5 on 2023-01-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reg_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
