# Generated by Django 4.1.5 on 2023-01-16 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0003_initial'),
        ('Vehicle', '0002_alter_vehicle_parked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='parked_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Station.station'),
        ),
    ]
