# Generated by Django 4.1.5 on 2023-01-16 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehicle', '0001_initial'),
        ('Station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='Station.station'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='Station.station'),
        ),
    ]
