# Generated by Django 4.1.5 on 2023-01-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='drop_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
