# Generated by Django 4.1.5 on 2023-01-17 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0003_alter_transaction_drop_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='Station.station'),
        ),
    ]
