# Generated by Django 4.1.5 on 2023-01-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='cars',
            new_name='cars_parked',
        ),
        migrations.AddField(
            model_name='transaction',
            name='ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
