# Generated by Django 4.1.5 on 2023-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0004_rename_cars_station_cars_parked_transaction_ongoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
